name= comm_
version=1.0.0
author= yeep
maintainer= yeeep
sentence=Library for calibration value sending.
paragraph=Converts floats, scales, splits into bytes, and prints over serial.
category=Communication
